import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const rdkitSrc = resolve(__dirname, "node_modules/@rdkit/rdkit/dist");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  // Copy RDKit runtime files next to main.js
  copyFileSync(`${rdkitSrc}/RDKit_minimal.js`, "RDKit_minimal.js");
  copyFileSync(`${rdkitSrc}/RDKit_minimal.wasm`, "RDKit_minimal.wasm");
  console.log("Copied RDKit_minimal.js and RDKit_minimal.wasm");
  process.exit(0);
} else {
  // Dev mode: also copy so hot reload works
  copyFileSync(`${rdkitSrc}/RDKit_minimal.js`, "RDKit_minimal.js");
  copyFileSync(`${rdkitSrc}/RDKit_minimal.wasm`, "RDKit_minimal.wasm");
  await context.watch();
}
